/*
    Yet Another Graphics library
    Copyright (C) 2014 Andrew Zabolotny All Rights Reserved

    This code can be freely redistributed under the terms of
    GNU General Public License version 3 or later.
*/

#ifndef __GLBC_H__
#define __GLBC_H__

/**
 * @file glbc.h
 *      Layouts use a special bytecode to space-efficiently encode
 *      drawing operations required to display the layout. This file
 *      defines thees byte codes.
 *
 *      It is included from .S files generated by GOC, so anything
 *      that is not understood by the assembler must be enclosed
 *      into an #ifndef __ASSEMBLER__ block.
 */

/// (color code) set current drawing color
#define LOP_COLOR	0
/// (x, y) draw a dot
#define LOP_DOT		1
/// (x1, y1, x2, y2) draw a line
#define LOP_LINE	2
/// (x1, y1, x2, y2) draw a rectangle
#define LOP_RECT	3
/// (x1, y1, x2, y2) draw a filled box
#define LOP_BOX		4
/// (layout, x, y) draw another layout
#define LOP_DRAW	5
/// (text, x, y) draw a text string
#define LOP_TEXT	6
/// (menu, x, y) display a menu
#define LOP_MENU	7

#endif // __GLBC_H__
